name: universal-battery-limiter
base: core22
version: '2.2.0'
summary: Battery charge limit management for all laptops with animated icons
description: |
  A comprehensive battery charge limit management tool for all laptops
  with multiple interfaces including CLI, GUI, and system tray integration.
  
  NEW in v2.2.0: Beautiful animated system tray icons that respond to battery state!

  Features:
  - Interactive CLI with colored output and presets
  - Modern GUI application with theme-aware styling
  - Animated system tray icons (charging, low battery, limit reached, etc.)
  - System tray indicator for quick access
  - Modern GUI application with dark theme
  - System tray indicator for quick access
  - Battery status monitoring
  - Support for 50-100% charge limits
  - Quick preset options (60%, 70%, 80%, 90%, 100%)
  - Automatic update checking from GitHub
  - Auto-start system tray integration

# Snap Store metadata
website: https://github.com/FrancyAlinston/Laptop-Battery-Limiter
source-code: https://github.com/FrancyAlinston/Laptop-Battery-Limiter
issues: https://github.com/FrancyAlinston/Laptop-Battery-Limiter/issues
donation: https://github.com/sponsors/FrancyAlinston
contact: francyalen@gmail.com
license: MIT
title: Universal Battery Limiter
icon: snap/gui/battery-limiter.svg

# Package metadata
grade: stable
confinement: strict

plugs:
  battery-control:
    interface: system-files
    read:
      - /sys/class/power_supply/BAT0/capacity
      - /sys/class/power_supply/BAT0/status
      - /sys/class/power_supply/BAT0/charge_control_end_threshold
    write:
      - /sys/class/power_supply/BAT0/charge_control_end_threshold

parts:
  universal-battery-limiter:
    plugin: dump
    source: .
    organize:
      battery-cli: bin/battery-cli
      battery-limit: bin/battery-limit
      battery-gui: bin/battery-gui
      battery-indicator: bin/battery-indicator
      set-charge-limit.sh: bin/set-charge-limit.sh
    stage-packages:
      - python3
      - python3-gi
      - python3-gi-cairo
      - gir1.2-gtk-3.0
      - gir1.2-appindicator3-0.1
      - gir1.2-notify-0.7
      - python3-tk

apps:
  battery-cli:
    command: bin/battery-cli
    plugs: [battery-control]

  battery-limit:
    command: bin/battery-limit
    plugs: [battery-control]

  battery-gui:
    command: bin/battery-gui
    extensions: [gnome]
    plugs: [battery-control, home]

  battery-indicator:
    command: bin/battery-indicator
    extensions: [gnome]
    plugs: [battery-control, home]
    daemon: simple
    restart-condition: always
