name: universal-battery-limiter
base: core22
version: '2.0.0'
summary: Battery charge limit management for all laptops
description: |
  A comprehensive battery charge limit management tool for all laptops 
  with multiple interfaces including CLI, GUI, and system tray integration.
  
  Features:
  - Interactive CLI with colored output and presets
  - Modern GUI application with dark theme  
  - System tray indicator for quick access
  - Battery status monitoring
  - Support for 50-100% charge limits
  - Quick preset options (60%, 70%, 80%, 90%, 100%)
  - Automatic update checking from GitHub
  - Auto-start system tray integration

grade: stable
confinement: classic

parts:
  universal-battery-limiter:
    plugin: dump
    source: .
    organize:
      battery-cli: bin/battery-cli
      battery-limit: bin/battery-limit
      battery-gui: bin/battery-gui
      battery-indicator: bin/battery-indicator
      set-charge-limit.sh: bin/set-charge-limit.sh
    stage-packages:
      - python3
      - python3-gi
      - python3-gi-cairo
      - gir1.2-gtk-3.0
      - gir1.2-appindicator3-0.1
      - gir1.2-notify-0.7
      - python3-tk
      - policykit-1

apps:
  battery-cli:
    command: bin/battery-cli
    
  battery-limit:
    command: bin/battery-limit
    
  battery-gui:
    command: bin/battery-gui
    extensions: [gnome]
    
  battery-indicator:
    command: bin/battery-indicator
    extensions: [gnome]
    daemon: simple
    restart-condition: always
